Chat App
beyond-io/sellotape pull request #31
Opened 2020-09-14 19:14 UTC by tarelmadar

Chat App-
It this PR I demonstrating streamer's chat channel.
First, the user types the chat room name(streamer's chat page) he would like to enter.
The user transfers to a specific room, where he can talk with other users and the streamer itself.

2020-09-15 05:30 UTC, ifireball commented
Since a previous PR I've seen about chat was much bigger I suspect this is not the entire chat app but a small part of it - but I'm aftraid the PR titme and description do not help me to understand what is included in this PR exactly. - also at 12 files and 163 lines - it is a little big.

2020-09-15 16:30 UTC, lioramilbaum requested changes
link the issue as I've suggested over Slack today

2020-09-15 16:30 UTC, lioramilbaum commented on sellotape/sellotape_dj/chat/templates/chat/room.html
> +</html>
newline is missing

2020-09-15 16:30 UTC, lioramilbaum commented on sellotape/sellotape_dj/chat/urls.py
> +]
newline

2020-09-15 16:30 UTC, lioramilbaum commented on sellotape/sellotape_dj/chat/views.py
> +    })
newline

2020-09-15 16:44 UTC, lioramilbaum requested changes

2020-09-15 16:44 UTC, lioramilbaum commented on sellotape/sellotape_dj/chat/consumers.py
> +        }))
newline :-)

2020-09-15 16:44 UTC, lioramilbaum commented on sellotape/sellotape_dj/chat/views.py
> +
something is wrong with the newline

2020-09-15 16:44 UTC, lioramilbaum commented on sellotape/sellotape_dj/chat/views.py
> +
You might want to run flake8 on all files

2020-09-15 16:44 UTC, lioramilbaum commented on sellotape/sellotape_dj/chat/templates/chat/index.html
> +</html>
newline

2020-09-15 16:44 UTC, lioramilbaum commented on sellotape/sellotape_dj/chat/routing.py
> +]
newline

2020-09-15 18:11 UTC, tarelmadar reviewed
fixes using flake8

2020-09-17 11:36 UTC, lioramilbaum requested changes
Please link an issue to the PR

2020-09-17 11:44 UTC, lioramilbaum commented on sellotape/sellotape_dj/chat/views.py
> +
??

2020-09-17 12:18 UTC, closed without merging