Login page
beyond-io/sellotape pull request #45
Opened 2020-09-25 12:26 UTC by 11galpid

This PR introduces the login page template, it uses the common parts (navigation, header and footer)
it uses django's base Login and Logout template url views and implements upon them (logout doesn't need a view, login does)
Routing is adjusted in the settings & urls accordingly

For debugging purposes, I've added the manual login option with user & pass, in production environment only facebook & google will remain

2020-09-25 13:53 UTC, rosomri approved these changes

2020-09-28 15:19 UTC, alonweissfeld approved these changes

2020-09-29 06:13 UTC, ifireball requested changes
Please resolve the merge conflicts that GitHub is warns you about

2020-09-29 06:25 UTC, 11galpid commented
Conflicts resolved

2020-09-29 10:11 UTC, ifireball approved these changes
LGTM

2020-09-29 10:16 UTC, merged