Explore page
beyond-io/sellotape pull request #87
Opened 2020-11-05 22:35 UTC by rosomri

I have had problem with migration, PR it as draft

2020-11-06 18:06 UTC, alonweissfeld requested changes
Great work!

However I think there should be more meaningful variable names before merging. The names should be more descriptive and helpful to understand what's going on :)

2020-11-06 18:06 UTC, alonweissfeld commented on sellotape/sellotape_dj/main_app/models.py
> +    class Foo(models.IntegerChoices):
Foo?

2020-11-06 18:06 UTC, alonweissfeld commented on sellotape/sellotape_dj/main_app/views.py
> +    # genre_streams = dict((genre['genre'], Stream.objects.all().filter(genre=genre['genre'])) for genre in genres)
Do we need those for some reference here? If so add a comment, otherwise delete :)

2020-11-06 18:06 UTC, alonweissfeld commented on sellotape/sellotape_dj/main_app/views.py
> +        'top_rated': top_rated,
Since there is a mix of different objects (streams and users), I think it is important to have explicit names. For example `top_rated_users`

2020-11-06 18:06 UTC, alonweissfeld commented on sellotape/sellotape_dj/main_app/templates/explore.html
> +                    {% for top in top_rated %}
What is `top`? Is that a user profile? Please use meaningful names - it will help the readability! :)

2020-11-07 07:57 UTC, rosomri commented on sellotape/sellotape_dj/main_app/models.py
> +    class Foo(models.IntegerChoices):
local class, it is not used after generating genre field,
I changed it anyway

2020-11-07 08:13 UTC, rosomri commented
> Great work!
> 
> However I think there should be more meaningful variable names before merging. The names should be more descriptive and helpful to understand what's going on :)
> 
> Also, maybe rebase the commits?

@alonweissfeld I fixed all the required changes.
This PR  is still a work in progress and currently a draft, I will rebase the commits later ;)

2020-11-07 10:48 UTC, closed without merging